{"uid":"2524b991e5987662","name":"同时删除3个节目","fullName":"test_case.test_program_management.TestProgramManagement#test_multi_delete_three_program","historyId":"f5f2620e286e54ede35bcac603d79ebd","time":{"start":1714992969308,"stop":1714992969308,"duration":0},"status":"skipped","statusMessage":"Skipped: 多选时报错","statusTrace":"('D:\\\\ui\\\\test_case\\\\test_program_management.py', 390, 'Skipped: 多选时报错')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1714992087297,"stop":1714992099981,"duration":12684},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"env","time":{"start":1714992087297,"stop":1714992087297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"program_management_set_up","time":{"start":1714992969957,"stop":1714992969957,"duration":0},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.hkciot.com', port=443): Max retries exceeded with url: /cuteview/program/getInPage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002031BC08730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ui\\test_case\\test_program_management.py\", line 24, in program_management_set_up\n    programlist.get_program_list_ids()\n  File \"D:\\ui\\common\\set_up_program_list.py\", line 24, in get_program_list_ids\n    response = requests.post(url=base_url,headers=self.headers,data=json.dumps(body))\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0},{"name":"program_page","time":{"start":1714992969957,"stop":1714992969957,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0}],"afterStages":[{"name":"program_page::0","time":{"start":1714992970027,"stop":1714992970027,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"driver::0","time":{"start":1714992971911,"stop":1714992971911,"duration":0},"status":"broken","statusMessage":"pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'rm-wz9vq722u8axcvo06oo.mysql.rds.aliyuncs.com' ([Errno 11001] getaddrinfo failed)\")\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\ui\\conftest.py\", line 36, in driver\n    sql_execute()\n  File \"D:\\ui\\data_clean.py\", line 8, in sql_execute\n    connection = pymysql.connect(host=host, port=3391, user='hkc_cv_user', password='Hkc285$$', database='hkc_cv')\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 358, in __init__\n    self.connect()\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 711, in connect\n    raise exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0}],"labels":[{"name":"feature","value":"program management"},{"name":"epic","value":"项目hkc"},{"name":"tag","value":"run(order=14)"},{"name":"tag","value":"@pytest.mark.skip(reason='多选时报错')"},{"name":"tag","value":"@pytest.mark.usefixtures('program_management_set_up')"},{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_program_management"},{"name":"subSuite","value":"TestProgramManagement"},{"name":"host","value":"hkc0208725"},{"name":"thread","value":"26752-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_program_management"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.skip(reason='多选时报错')","run(order=14)","@pytest.mark.usefixtures('program_management_set_up')"]},"source":"2524b991e5987662.json","parameterValues":[]}