{"uid":"89952361ef26ebf6","name":"发布管理：选择一个设备","fullName":"test_case.test_release_management.TestReleaseStrategy#test_choose_terminal_release","historyId":"eaeba2835025f419ba55ae3f12c611f9","time":{"start":1714992887326,"stop":1714992887326,"duration":0},"status":"skipped","statusMessage":"Skipped: >           terminal_page.switch_to_terminal_center()","statusTrace":"('D:\\\\ui\\\\test_case\\\\test_release_management.py', 238, 'Skipped: >           terminal_page.switch_to_terminal_center()')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1714992087297,"stop":1714992099981,"duration":12684},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"env","time":{"start":1714992087297,"stop":1714992087297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"driver","time":{"start":1714992250058,"stop":1714992260927,"duration":10869},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"release_page","time":{"start":1714992887291,"stop":1714992887291,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF6ED1078A2+54818]\n\t(No symbol) [0x00007FF6ED076AD2]\n\t(No symbol) [0x00007FF6ECF2D8ED]\n\t(No symbol) [0x00007FF6ECF630DE]\n\t(No symbol) [0x00007FF6ECF8E9A2]\n\t(No symbol) [0x00007FF6ECF8A710]\n\t(No symbol) [0x00007FF6ECF8A016]\n\t(No symbol) [0x00007FF6ECF041D0]\n\tGetHandleVerifier [0x00007FF6ED46B9A2+3610402]\n\tGetHandleVerifier [0x00007FF6ED4C1870+3962352]\n\tGetHandleVerifier [0x00007FF6ED4B9D5F+3930847]\n\tGetHandleVerifier [0x00007FF6ED1A3656+693206]\n\t(No symbol) [0x00007FF6ED081638]\n\t(No symbol) [0x00007FF6ECF02FFE]\n\tGetHandleVerifier [0x00007FF6ED502288+4227080]\n\tBaseThreadInitThunk [0x00007FFEE159257D+29]\n\tRtlUserThreadStart [0x00007FFEE202AA58+40]\n\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\ui\\test_case\\test_release_management.py\", line 26, in release_page\n    window_size = release_page.get_window_size()\n  File \"D:\\ui\\basepage\\base_page.py\", line 68, in get_window_size\n    width = self.driver.get_window_size().get('width')\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 877, in get_window_size\n    size = self.get_window_rect()\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_window_rect\n    return self.execute(Command.GET_WINDOW_RECT)[\"value\"]\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0}],"afterStages":[{"name":"driver::0","time":{"start":1714992971911,"stop":1714992971911,"duration":0},"status":"broken","statusMessage":"pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'rm-wz9vq722u8axcvo06oo.mysql.rds.aliyuncs.com' ([Errno 11001] getaddrinfo failed)\")\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\ui\\conftest.py\", line 36, in driver\n    sql_execute()\n  File \"D:\\ui\\data_clean.py\", line 8, in sql_execute\n    connection = pymysql.connect(host=host, port=3391, user='hkc_cv_user', password='Hkc285$$', database='hkc_cv')\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 358, in __init__\n    self.connect()\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 711, in connect\n    raise exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0},{"name":"driver::0","time":{"start":1714992971927,"stop":1714992971927,"duration":0},"status":"broken","statusMessage":"pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'rm-wz9vq722u8axcvo06oo.mysql.rds.aliyuncs.com' ([Errno 11001] getaddrinfo failed)\")\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\ui\\conftest.py\", line 36, in driver\n    sql_execute()\n  File \"D:\\ui\\data_clean.py\", line 8, in sql_execute\n    connection = pymysql.connect(host=host, port=3391, user='hkc_cv_user', password='Hkc285$$', database='hkc_cv')\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 358, in __init__\n    self.connect()\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 711, in connect\n    raise exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0}],"labels":[{"name":"feature","value":"release management"},{"name":"epic","value":"项目hkc"},{"name":"tag","value":"@pytest.mark.usefixtures('add_terminal')"},{"name":"tag","value":"run(order=8)"},{"name":"tag","value":"@pytest.mark.skip('>           terminal_page.switch_to_terminal_center()')"},{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_release_management"},{"name":"subSuite","value":"TestReleaseStrategy"},{"name":"host","value":"hkc0208725"},{"name":"thread","value":"26752-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_release_management"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.skip('>           terminal_page.switch_to_terminal_center()')","@pytest.mark.usefixtures('add_terminal')","run(order=8)"]},"source":"89952361ef26ebf6.json","parameterValues":[]}