{"uid":"d0d8b735afd79b72","name":"登录成功","fullName":"test_case.test_testin_login.TestLogin#test_login_ddt","historyId":"2ab0b23982e60a92680b98d43c9da54f","time":{"start":1714992336306,"stop":1714992340980,"duration":4674},"description":"测试登录模块","descriptionHtml":"<p>测试登录模块</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1714992087297,"stop":1714992099981,"duration":12684},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"env","time":{"start":1714992087297,"stop":1714992087297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"env","time":{"start":1714992326211,"stop":1714992326211,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"login_page","time":{"start":1714992326211,"stop":1714992326211,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0}],"afterStages":[{"name":"login_page::0","time":{"start":1714992356288,"stop":1714992356288,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0},{"name":"driver::0","time":{"start":1714992971911,"stop":1714992971911,"duration":0},"status":"broken","statusMessage":"pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'rm-wz9vq722u8axcvo06oo.mysql.rds.aliyuncs.com' ([Errno 11001] getaddrinfo failed)\")\n","statusTrace":"  File \"D:\\sw_install\\python-install\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\ui\\conftest.py\", line 36, in driver\n    sql_execute()\n  File \"D:\\ui\\data_clean.py\", line 8, in sql_execute\n    connection = pymysql.connect(host=host, port=3391, user='hkc_cv_user', password='Hkc285$$', database='hkc_cv')\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 358, in __init__\n    self.connect()\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pymysql\\connections.py\", line 711, in connect\n    raise exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0}],"labels":[{"name":"feature","value":"login-test"},{"name":"epic","value":"项目hkc"},{"name":"tag","value":"run(order=1)"},{"name":"tag","value":"@pytest.mark.usefixtures('env')"},{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_testin_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"hkc0208725"},{"name":"thread","value":"26752-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_testin_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"case","value":"[3, '错误的手机号、正确的密码，登录失败', 13715297700, 'Aa12345678', 'y', None, '用户名或密码错误']"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["run(order=1)","@pytest.mark.usefixtures('env')"]},"source":"d0d8b735afd79b72.json","parameterValues":["[3, '错误的手机号、正确的密码，登录失败', 13715297700, 'Aa12345678', 'y', None, '用户名或密码错误']"]}