{"uuid": "9e8bcdfe-2373-46a0-9818-de1d408bf7ce", "children": ["66997776-6b26-4ccf-b9c7-ed26a26bbe3d"], "befores": [{"name": "init_play_bill", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF70D2C78A2+54818]\n\t(No symbol) [0x00007FF70D236AD2]\n\t(No symbol) [0x00007FF70D0ED8ED]\n\t(No symbol) [0x00007FF70D1230DE]\n\t(No symbol) [0x00007FF70D14E9A2]\n\t(No symbol) [0x00007FF70D14A710]\n\t(No symbol) [0x00007FF70D14A016]\n\t(No symbol) [0x00007FF70D0C41D0]\n\tGetHandleVerifier [0x00007FF70D62B9A2+3610402]\n\tGetHandleVerifier [0x00007FF70D681870+3962352]\n\tGetHandleVerifier [0x00007FF70D679D5F+3930847]\n\tGetHandleVerifier [0x00007FF70D363656+693206]\n\t(No symbol) [0x00007FF70D241638]\n\t(No symbol) [0x00007FF70D0C2FFE]\n\tGetHandleVerifier [0x00007FF70D6C2288+4227080]\n\tBaseThreadInitThunk [0x00007FFEE159257D+29]\n\tRtlUserThreadStart [0x00007FFEE202AA58+40]\n\n", "trace": "  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ui\\test_case\\test_play_bill.py\", line 49, in init_play_bill\n    terminal_page.add_new_terminal()\n  File \"D:\\ui\\pageobject\\terminal_page.py\", line 34, in add_new_terminal\n    self.switch_to_terminal_center()\n  File \"D:\\ui\\pageobject\\terminal_page.py\", line 21, in switch_to_terminal_center\n    focus_ele = self.get_element(focus)\n  File \"D:\\ui\\basepage\\base_page.py\", line 126, in get_element\n    w_element = self.driver.find_element(By.XPATH, value=args_value)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1714961614744, "stop": 1714961615120}], "start": 1714961614744, "stop": 1714961615213}