{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[5, '正确的账号、错误的密码，登录失败', 'uitest', 12345678, 'y', None, '用户名或密码错误']"}], "start": 1719813660332, "stop": 1719813662447, "uuid": "56e0ec76-1348-452a-9981-1b1a40374753", "historyId": "f6857851da9de381510c1bb0141d9c78", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "feature", "value": "login-test"}, {"name": "epic", "value": "项目hkc"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "37996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}