{"uuid": "66eb16a2-fa40-45d2-bf5d-8053494b813c", "children": ["b3c3ffb2-c166-4529-9894-307c7d9c0599"], "befores": [{"name": "init_play_bill", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF6ED1078A2+54818]\n\t(No symbol) [0x00007FF6ED076AD2]\n\t(No symbol) [0x00007FF6ECF2D8ED]\n\t(No symbol) [0x00007FF6ECF630DE]\n\t(No symbol) [0x00007FF6ECF8E9A2]\n\t(No symbol) [0x00007FF6ECF8A710]\n\t(No symbol) [0x00007FF6ECF8A016]\n\t(No symbol) [0x00007FF6ECF041D0]\n\tGetHandleVerifier [0x00007FF6ED46B9A2+3610402]\n\tGetHandleVerifier [0x00007FF6ED4C1870+3962352]\n\tGetHandleVerifier [0x00007FF6ED4B9D5F+3930847]\n\tGetHandleVerifier [0x00007FF6ED1A3656+693206]\n\t(No symbol) [0x00007FF6ED081638]\n\t(No symbol) [0x00007FF6ECF02FFE]\n\tGetHandleVerifier [0x00007FF6ED502288+4227080]\n\tBaseThreadInitThunk [0x00007FFEE159257D+29]\n\tRtlUserThreadStart [0x00007FFEE202AA58+40]\n\n", "trace": "  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ui\\test_case\\test_play_bill.py\", line 52, in init_play_bill\n    terminal_page.add_new_terminal()\n  File \"D:\\ui\\pageobject\\terminal_page.py\", line 34, in add_new_terminal\n    self.switch_to_terminal_center()\n  File \"D:\\ui\\pageobject\\terminal_page.py\", line 21, in switch_to_terminal_center\n    focus_ele = self.get_element(focus)\n  File \"D:\\ui\\basepage\\base_page.py\", line 126, in get_element\n    w_element = self.driver.find_element(By.XPATH, value=args_value)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1714991917790, "stop": 1714991918171}], "start": 1714991917790, "stop": 1714991918293}